application: idibishe
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /fonts
  static_dir: fonts
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /.*
  script: TOS.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
